-- MySQL Script generated by MySQL Workbench
-- Sun Mar  5 20:17:09 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema procook
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `procook` ;

-- -----------------------------------------------------
-- Schema procook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `procook` ;
USE `procook` ;

-- -----------------------------------------------------
-- Table `procook`.`amazon_mws_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `procook`.`amazon_mws_orders` ;

CREATE TABLE IF NOT EXISTS `procook`.`amazon_mws_orders` (
  `amo_uid` INT NOT NULL AUTO_INCREMENT,
  `amo_AmazonOrderId` VARCHAR(45) NULL,
  `amo_PurchaseDate` VARCHAR(45) NULL,
  `amo_OrderStatus` VARCHAR(45) NULL,
  `amo_FulfillmentChannel` VARCHAR(45) NULL,
  `amo_OrderTotal` VARCHAR(45) NULL,
  `amo_OrderTotalCurrency` VARCHAR(45) NULL,
  `amo_BuyerName` VARCHAR(45) NULL,
  `amo_BuyerEmail` VARCHAR(45) NULL,
  `amo_ShipmentServiceLevelCategory` VARCHAR(45) NULL,
  `amo_OrderType` VARCHAR(45) NULL,
  `amo_ShippingAddressName` VARCHAR(45) NULL,
  `amo_ShippingAddressLine1` VARCHAR(45) NULL,
  `amo_ShippingAddressLine2` VARCHAR(45) NULL,
  `amo_ShippingAddressLine3` VARCHAR(45) NULL,
  `amo_ShippingAddressCity` VARCHAR(45) NULL,
  `amo_ShippingAddressCounty` VARCHAR(45) NULL,
  `amo_ShippingAddressDistrict` VARCHAR(45) NULL,
  `amo_ShippingAddressStateOrRegion` VARCHAR(45) NULL,
  `amo_ShippingAddressPostalCode` VARCHAR(45) NULL,
  `amo_ShippingAddressCountryCode` VARCHAR(45) NULL,
  `amo_ShippingAddressPhone` VARCHAR(45) NULL,
  `amo_IsPrime` VARCHAR(45) NULL,
  PRIMARY KEY (`amo_uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `procook`.`amazon_mws_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `procook`.`amazon_mws_items` ;

CREATE TABLE IF NOT EXISTS `procook`.`amazon_mws_items` (
  `ami_uid` INT NOT NULL AUTO_INCREMENT,
  `ami_amo_uid` INT NOT NULL,
  `ami_ASIN` VARCHAR(45) NULL,
  `ami_SellerSKU` VARCHAR(45) NULL,
  `ami_Title` VARCHAR(45) NULL,
  `ami_QuantityOrdered` VARCHAR(45) NULL,
  `ami_ItemPriceValue` VARCHAR(45) NULL,
  `ami_ItemPriceCurrency` VARCHAR(45) NULL,
  `ami_ShippingPriceValue` VARCHAR(45) NULL,
  `ami_ShippingPriceCurrrency` VARCHAR(45) NULL,
  PRIMARY KEY (`ami_uid`),
  INDEX `ami_amo_idx` (`ami_amo_uid` ASC),
  CONSTRAINT `ami_amo`
    FOREIGN KEY (`ami_amo_uid`)
    REFERENCES `procook`.`amazon_mws_orders` (`amo_uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
